/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    CommonEmpty: typeof import('./../components/CommonEmpty.vue')['default']
    CommonForm: typeof import('./../components/CommonForm.vue')['default']
    CommonHeader: typeof import('./../components/CommonHeader.vue')['default']
    CommonLoading: typeof import('./../components/CommonLoading.vue')['default']
    CommonTable: typeof import('./../components/CommonTable.vue')['default']
    GlobalEmpty: typeof import('./../components/GlobalEmpty.vue')['default']
    GlobalForm: typeof import('./../components/GlobalForm/GlobalForm.vue')['default']
    GlobalHeader: typeof import('./../components/GlobalHeader/GlobalHeader.vue')['default']
    GlobalLoading: typeof import('./../components/GlobalLoading.vue')['default']
    GlobalTable: typeof import('./../components/GlobalTable/GlobalTable.vue')['default']
    LoadingMask: typeof import('./../components/LoadingMask.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserLoginStatus: typeof import('./../components/GlobalHeader/components/UserLoginStatus.vue')['default']
  }
}
