/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    GlobalHeader: typeof import('./../components/GlobalHeader/GlobalHeader.vue')['default']
    LoadingMask: typeof import('./../components/LoadingMask.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserLoginStatus: typeof import('./../components/GlobalHeader/components/UserLoginStatus.vue')['default']
  }
}
